spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-propert-inclusion: non_null

jwt:
  secret: 98q3474318-019384jrd981384ru891348ur19384
  expiration: 3600000 # 1 hora em milissegundos