spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-propert-inclusion: non_null

jwt:
  secret: 98q3474318-019384jrd981384ru891348ur19384
  expiration: 3600000 # 1 hora em milissegundos